### PR TITLE
Change order to fix z-auto issue on mobile menu

### PR DESCRIPTION
**Pull request by lmachens**

### CODE REVIEW

**Comment by glazk0** [comment]
I would you to change the `items-center` to `justify-center`, it would be better. 

Otherwise that's perfect!

**Comment by lmachens** [comment]
> I would you to change the `items-center` to `justify-center` [here](https://github.com/lmachens/hogwarts.gg/blob/fix/z-order/ui/GlobalUser.tsx#L86) , it would be better.
> 
> Otherwise that's perfect!

For me, it looks not better because the font is not aligned anymore. 
image

**Comment by glazk0** [comment]
> > I would you to change the `items-center` to `justify-center` [here](https://github.com/lmachens/hogwarts.gg/blob/fix/z-order/ui/GlobalUser.tsx#L86) , it would be better.
> > Otherwise that's perfect!
> 
> For me, it looks not better because the font is not aligned anymore. image

Oh my bad, gonna fix this! But otherwise, when it will have aligned fonts / text, do you like it or no ?

**Comment by lmachens** [comment]
I think the font should be aligned with the icon :)

**Pull request merged**
